In [125]:
import numpy as np

In [126]:
def fitness_calculation(individual):
    """Calculate fitness for individual"""
    x = individual
    result = (x[3]**1)*(x[4]**1) + x[2]*x[3]*x[4]**2 + x[3] + x[1]*x[3] + \
             (x[1]**2)*(x[2]**1)*(x[3]**2)*x[4] + 50
    return abs(result)

In [127]:
def make_individual(number_of_genes, lower_limit, upper_limit):
    """Make individual"""
    individual = np.random.randint(lower_limit, upper_limit, number_of_genes)
    return individual

In [128]:
def make_first_population(number_of_individuals, number_of_genes = 5, lower_limit = -100, upper_limit = 100):
    """Make first population"""
    population = [make_individual(number_of_genes, lower_limit, upper_limit) for _ in range(number_of_individuals)]
    return population

In [129]:
def selection(population):
    survived_individuals = []
    np.random.shuffle(population)
    for i in range(0,len(population)-1,2):
        if abs(fitness_calculation(population[i])) < abs(fitness_calculation(population[i+1])):
            survived_individuals.append(population[i])
        else:
            survived_individuals.append(population[i+1])
    return survived_individuals

In [130]:
def pairing(selected):
    parents = []
    for i in range(2):
        np.random.shuffle(selected)
        for i in range(0, len(selected)-1,2):
            parents.append([selected[i],selected[i+1]])
    return parents

In [131]:
def single_point_mating(parents, point=3,p1=0.1,p2=0.1):
    children = []
    children.append(np.array(list(parents[0][:point])+list(parents[1][point:])))
    children.append(np.array(list(parents[1][:point])+list(parents[0][point:])))
    return children

In [132]:
def two_points_mating(parents, point_1 = 2, point_2 = 4):
    children = []
    children.append(np.array(list(parents[0][:point_1])+list(parents[1][point_1:point_2])+list(parents[0][point_2:])))
    children.append(np.array(list(parents[1][:point_1])+list(parents[0][point_1:point_2])+list(parents[1][point_2:])))
    return children

In [133]:
def mutation(child, p1 = 0.10,p2 = 0.2):
    new_child = []
    for i in child:
        if np.random.uniform() <= p1:
            new_child.append(np.random.randint(-300,300))
        elif np.random.uniform() <= p2:
            new_child.append(np.random.randint(-300,300))
        else:
            new_child.append(i)
    return np.array(new_child)

In [135]:
population = make_first_population(10,5,-300,300)
for i in range(100):
    selected_population = selection(population)
    parents = pairing(selected_population)
    children = []
    for pair in parents:
        single_child = single_point_mating(pair)
        multi_child = two_points_mating(pair)
        children.append(single_child[0])
        children.append(single_child[1])
        children.append(multi_child[0])
        children.append(multi_child[1])
    new_children = []
    for child in children:
        new_children.append(mutation(child))
    arr = []
    for child in new_children:
        arr.append(fitness_calculation(child))
    arr = np.array(arr)
    new_children = np.array(new_children)
    arr1inds = arr.argsort()
    sorted_arr = arr[arr1inds[::1]]
    sorted_new_children = new_children[arr1inds[::1]]
    new_chil = [np.array(c) for c in sorted_new_children]
    population = new_chil[:10]
    print('----------------------------')
    for p in population:
        print(p)

C:\Users\Windows10x64\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in long_scalars
  """


----------------------------
[ 181  188 -201  293  -31]
[-146 -300 -276  286 -217]
[-130  188  -39 -278 -143]
[ 163 -106  110  164  -65]
[-296 -300 -183 -105  198]
[-146 -300  -80 -278 -217]
[163   9 251  28 194]
[  -4  188 -269  293  246]
[ 163    9  251 -139 -217]
[ 286    9  -39 -262  -65]
----------------------------
[-146 -300 -276 -278 -217]
[-296 -300 -183 -278 -143]
[-130  188  -39  293  -31]
[-146   53 -276  286  288]
[ 181  188  122 -278  -24]
[-146 -300 -183   98  198]
[-146 -300  -80 -175 -217]
[-146 -300  134  135 -217]
[-130  188 -183 -105 -143]
[   8 -300  -80   79  -18]
----------------------------
[-146   18 -276  164 -217]
[-146  -83 -248  252   -8]
[181 188 122 293 -31]
[-268   53 -276 -278  -24]
[ 181  133  122  286 -182]
[-146 -300 -276  139  288]
[-146 -300 -276 -197 -217]
[ -83   53 -276 -278  288]
[-261  188  -39 -278  252]
[-146 -300 -257  293 -176]
----------------------------
[-146 -200 -276   48   77]
[-268   53 -276 -129  -24]
[-146 -278 -248  252 -270]
[-1

----------------------------
[ 42 292  86   0 193]
[  70 -112  275    0 -297]
[  -2  292  275    0 -297]
[ -18 -242   86    0  193]
[ 133 -112 -262    0  101]
[ 231  -28  244    0 -154]
[ -18 -112 -262    0  227]
[-231 -112  277    0 -154]
[ -18 -112  275    0 -154]
[ -18 -112 -262    0  193]
----------------------------
[-231 -112   82    0  193]
[ 231 -112 -262    0 -154]
[-231 -112 -262    0   -8]
[-256 -252  -53    0 -297]
[ 133 -112 -262    0 -297]
[ 70  87 275   0 101]
[ 133 -112  275    0  101]
[-276 -112 -262    0 -154]
[-18 153 277   0 193]
[ -74 -112 -262  216 -297]
----------------------------
[ 231 -112 -262    0 -141]
[ 263 -252  -53    0  264]
[ 231 -120  -53    0  163]
[-256 -252 -262    0 -297]
[ 133 -112  275    0  101]
[-146  104  275    0  -72]
[ 133 -112  275    0  101]
[-23  87 259   0 101]
[-231 -112  -39    0 -154]
[-289 -112 -262    0  193]
----------------------------
[ 231 -112 -262    0  163]
[ 231 -164  -53    0 -186]
[ 231 -120 -262    0  163]
[-23  87 259 

In [136]:
fitness_calculation([-246,-120,-43,0,-227])

50